#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

alias ssh="mosh"
alias gs="git status"
alias gp="git pull"
alias gd="git diff"
alias ga="git add -p"
alias gc="git checkout"
alias mach="~/build/mozilla-central/mach"
